### DISCUSSION TITLE
Automation loop through cameras

### DISCUSSION THREAD

**Discussion by tuanha2000vn** [robmarkcole/HASS-Deepstack#234] [General]
It's possible to make an automation trigger on scan completed?

I want to make an automation that loop through camera.

Scan Camera 1... Done => Process Camera 2
Scan Camera 2... Done => Process Camera 3
...
Scan Camera N... Done => Process Camera 1

Thank.

**Comment by tuanha2000vn** [comment]
Look like i found a way, using watch folder for modified file

Thank for the great repo, happy tweaking.
```
- alias: "File Updated Alert"
  initial_state: true
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: modified
  action:
  - service: system_log.write
    data_template:
      level: error
      logger: homeassistant.components.mylogger
      message: "{{ now().strftime('%S.%f') [:-4] }} modified {{ trigger.event.data.file }} in {{ trigger.event.data.folder }} file:{{ trigger.event.data.path }}"
```
