### DISCUSSION TITLE
Improve Home Assistant Processing Time

### DISCUSSION THREAD

**Discussion by tuanha2000vn** [robmarkcole/HASS-Deepstack#238] [General]
Hi, I've made a simple automation that scan camera repeatly, I've notice the deep stack processing time is really fast on the Jetson Nano.

However, the total processing of Home Assistant is very high.

## This is the automation
```
- id: "1618637076001"
  alias: DeepStack Scan Camera 1
  description: Scan All Camera
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: automation.deepstack_scan_camera_1
      to: "on"
  condition: []
  action:
    - service: image_processing.scan
      data: {}
      target:
        entity_id:
          - image_processing.camera_1
    - service: system_log.write
      data:
        level: warning
        message: "Cameras 1 scan interval {{ (as_timestamp(now()) - as_timestamp(states.input_text.deepstack_camera_1_last_scan.state)) | float | round(2) }} seconds"
    - service: input_text.set_value
      entity_id: input_text.deepstack_camera_1_last_scan
      data:
        value: "{{ now() }}"
    - service: automation.trigger
      target:
        entity_id: automation.deepstack_scan_camera_1
```

### Deepstack Docker Console: process image take 150 ms
```
[GIN] 2021/04/22 - 10:40:47 | 200 |  158.901916ms |   192.168.1.122 | POST     /v1/vision/detection
```

### Home Assistant Log: The loop take more than 2 second
```
[homeassistant.components.system_log.external] Cameras 1 scan interval 2.34 seconds
```
---
I guess the delay is due to Home Assistant take image from ffmeg stream and perform a http.post to deepstack server, processing returned data... 

What can I do to improve the Home Assistant processing time?

Thank you.
