### DISCUSSION TITLE
How do I add multiple cameras?

### DISCUSSION THREAD

**Discussion by bloupotlood** [robmarkcole/HASS-Deepstack#272] [Q&A] [answered]
Please help, I got everything running, but I don't understand how to add more than one camera? 

Thank you.

**Comment by robmarkcole** [comment, marked as answer]
You need to configure the integration for each camera separately

**Reply by bloupotlood** [reply]
> You need to configure the integration for each camera separately

Thank you very much, Rob, I figured it out!

In case anyone struggles with this, you have to encapsulate the _-platform: deepstack_object_ **repeatedly** under _image_processing:_ **for each** camera, taking great pain to make sure the indentation (spaces) is 100% correct as this yaml seems to actually use indentation as is.

As an example:
```
image_processing:
  - platform: deepstack_object
     <content>
     source:
       - entity_id: camera.first
  - platform: deepstack_object
     <content>
     source:
       - entity_id: camera.second
```
